---
layout: single
title: "에러 발생 해결 방법"
categories:
  - Anaconda
classes: wide
tags:
  - jeykll
  - github
  - Minimalmistakes
  - blog
  - Anaconda
---

# 제가 실행하면서 발생했던 에러들을 해결하는 방법들을 계속 업데이트할 포스팅입니다.

### 1. 파이토치 가상환경 구성 pip install 중 에러 발생  
 + pip install certifi==2019.11.28 을 할 때 다음과 같은 에러 발생
 `ERROR: Cannot uninstall 'certifi'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.`

 해결 방법
 `pip install --ignore-installed certifi==2019.11.28`

 --ignore 를 추가하여 해결


### 2. 아톰에서 가상환경 접속하여 사용할 때 에러 발생
 + 가상환경 접속 후 Shift + Enter를 반복 사용하다보면 에러 발생
 `[IPKernelApp] ERROR | Exception in message handler: Traceback (most recent call last): File "/venv/.virtualenvs/flask_dash/lib/python3..... 등 엄청 장문의 에러 발생`


 해결 방법
 `pip install jedi==0.17.2`

 jedi 버전을 다운그레이드 후 해결
